export const NEW_MILESTONES = [
  {
    order_index: 1,
    milestone_key: 'architect',
    label: 'Architecte',
    progress_percentage: 5,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 2,
    milestone_key: 'design_office',
    label: 'Bureau d\'étude',
    progress_percentage: 10,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 3,
    milestone_key: 'destruction_authorization_launch',
    label: 'Phase lancement autorisation destruction',
    progress_percentage: 15,
    is_conditional: true,
    condition_type: 'requires_destruction_authorization',
    is_enabled: false, // Désactivée par défaut
  },
  {
    order_index: 4,
    milestone_key: 'authorization_launch',
    label: 'Phase lancement autorisation',
    progress_percentage: 20,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 5,
    milestone_key: 'authorization_obtained',
    label: 'Obtention autorisation',
    progress_percentage: 25,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 6,
    milestone_key: 'laboratory',
    label: 'Laboratoire',
    progress_percentage: 30,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 7,
    milestone_key: 'control_office',
    label: 'Bureau de contrôle',
    progress_percentage: 35,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 8,
    milestone_key: 'existing_building_destruction',
    label: 'Destruction du bien existant',
    progress_percentage: 40,
    is_conditional: true,
    condition_type: 'has_existing_building',
    is_enabled: false, // Désactivée par défaut
  },
  {
    order_index: 9,
    milestone_key: 'structural_work',
    label: 'Gros œuvre',
    progress_percentage: 50,
    is_conditional: false,
    is_enabled: true,
  },
  // Sous-étapes du gros œuvre
  {
    order_index: 9.1,
    milestone_key: 'structural_work_foundation',
    label: 'Fondations',
    progress_percentage: 45,
    parent_key: 'structural_work',
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 9.2,
    milestone_key: 'structural_work_structure',
    label: 'Structure',
    progress_percentage: 48,
    parent_key: 'structural_work',
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 9.3,
    milestone_key: 'structural_work_walls',
    label: 'Murs et cloisons',
    progress_percentage: 50,
    parent_key: 'structural_work',
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 10,
    milestone_key: 'electricity',
    label: 'Électricité',
    progress_percentage: 55,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 11,
    milestone_key: 'plumbing',
    label: 'Plomberie',
    progress_percentage: 60,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 12,
    milestone_key: 'air_conditioning',
    label: 'Climatisation',
    progress_percentage: 65,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 13,
    milestone_key: 'plastering',
    label: 'Plâtrier',
    progress_percentage: 70,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 14,
    milestone_key: 'tiling',
    label: 'Carrelage',
    progress_percentage: 75,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 15,
    milestone_key: 'parquet',
    label: 'Parquet',
    progress_percentage: 80,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 16,
    milestone_key: 'woodwork',
    label: 'Boiserie',
    progress_percentage: 83,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 17,
    milestone_key: 'kitchen_installation',
    label: 'Installation cuisine',
    progress_percentage: 87,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 18,
    milestone_key: 'final_cleaning',
    label: 'Préparation de nettoyage fin de chantier',
    progress_percentage: 93,
    is_conditional: false,
    is_enabled: true,
  },
  {
    order_index: 19,
    milestone_key: 'eclat',
    label: 'Éclat',
    progress_percentage: 100,
    is_conditional: false,
    is_enabled: true,
  },
];
